
services:
  dev-db:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestdb
    networks:
      - sistemaMatricula
  test-db:
    image: postgres:latest
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestdb
    networks:
      - sistemaMatricula
networks:
  sistemaMatricula: